version: 2.1

jobs:
  test:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/PROJECT_TEST
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            echo PROJECT_TEST
            gcloud --version
  
workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - test
