version: 2.1
defaults: &defaults
  environment:
    PROJECT_TEST: odroidfeeder
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
jobs:
  Deploy:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    working_directory: /root/app
    steps:
      - checkout
      - run:
          name: "Google App Engine Deploy"
          command: |
           
            source .circleci/cicd-definitions.sh
            echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
            gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
            gcloud config set project ${GCLOUD_PROJECT_ID}
            
            echo "Checking if GCP Bucket is created..."
            echo "bucket must be named as: ${GCLOUD_PROJECT_BUCKET_NAME}"
            if [[ ! -z ${GCLOUD_PROJECT_BUCKET_NAME} ]]; then
              gsutil ls gs://${GCLOUD_PROJECT_BUCKET_NAME}/ || gsutil mb -c standard -p ${GCLOUD_PROJECT_ID} -l ${GCLOUD_PROJECT_REGION} gs://${GCLOUD_PROJECT_BUCKET_NAME}/
              gsutil rsync -x '^.*git.*$|^.*circleci.*$' -r ./ gs://${GCLOUD_PROJECT_BUCKET_NAME}/
            else
              exit -1
            fi
  
workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Deploy:
          <<: *only-releasable
