version: 2.1
defaults: &defaults
  working_directory: /root/app
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
jobs:
  Prepare:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "Google verify Authentication"
          command: |
           
            source .circleci/cicd-definitions.sh
            echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
            gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
            gcloud config set project ${GCLOUD_PROJECT_ID}
            
            #gsutil -m rsync -c -x '^.*git.*$|^.*circleci.*$' -r ./ gs://${GCLOUD_PROJECT_BUCKET_NAME}/
            
            #echo "Checking if GCP Bucket is created..."
            #echo "bucket must be named as: ${GCLOUD_PROJECT_BUCKET_NAME}"
            #if [[ ! -z ${GCLOUD_PROJECT_BUCKET_NAME} ]]; then
            ##  gsutil ls gs://${GCLOUD_PROJECT_BUCKET_NAME}/ || gsutil mb -c standard -p ${GCLOUD_PROJECT_ID} -l ${GCLOUD_PROJECT_REGION} gs://${GCLOUD_PROJECT_BUCKET_NAME}/
            #  #gsutil -m rsync -c -x '^.*git.*$|^.*circleci.*$' -r ./ gs://${GCLOUD_PROJECT_BUCKET_NAME}/
            #else
            ##  exit -1
            #fi
  Staging:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "Publish to Staging"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil ls gs://${GCLOUD_PROJECT_BUCKET_NAME}/

workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Prepare:
          <<: *only-releasable
          <<: *non-releasable
      - Staging:
          <<: *non-releasable
          requires:
            - Prepare
