version: 2.1
defaults: &defaults
  environment:
    PROJECT_TEST: odroidfeeder
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
jobs:
  Deploy:
  <<: *defaults
    docker:
      - image: google/cloud-sdk
    working_directory: ~/PROJECT_TEST
    steps:
      - checkout
      - run:
          name: "Google App Engine Deploy"
          command: |
            echo ${GCP_KEY} > del.json
            gcloud auth -q activate-service-account --key-file del.json
            gcloud config -q set project dynamic-nomad-223612
            gcloud app deploy -q app.yaml
  
workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Deploy:
        <<: *only-releasable
