version: 2.1
defaults: &defaults
  working_directory: /root/app

activate-sa: &activate-sa
  - run:
      name: "Activate SA to the Project"
      command: |
        source .circleci/cicd-definitions.sh
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
        gcloud config set project ${GCLOUD_PROJECT_ID}
revoke-sa: &revoke-sa
  - run:
      name: "Revoke SA"
      command: |
        source .circleci/cicd-definitions.sh
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        client_email=$(cat ${GCLOUD_JSON_KEY_PATH} | grep "client_email" | awk '{print $2}' | grep -o '".*"' | sed 's/"//g')
        echo "---------------------- $client_email"
        gcloud auth revoke ${client_email}

only-releasable: &only-releasable
  filters:
    branches:
      only:
        - release/gcp
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - release/gcp

jobs:
  Prepare Credentials:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *activate-sa

  GCP Sync:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "GCP Sync to Bucket"
          command: |
            source .circleci/cicd-definitions.sh
            echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
            gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
            gcloud config set project ${GCLOUD_PROJECT_ID}
            gsutil -m rsync -c -x '^.*git.*$|^.*circleci.*$' -r ./ gs://${GCLOUD_PROJECT_BUCKET_NAME}/
  
  GCP Bucket Update:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "GCP Bucket Update"
          command: |
            source .circleci/cicd-definitions.sh
            echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
            gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
            gcloud config set project ${GCLOUD_PROJECT_ID}
            gsutil acl ch -u AllUsers:R gs://${GCLOUD_PROJECT_BUCKET_NAME}/index.html
            gsutil acl ch -u AllUsers:R gs://${GCLOUD_PROJECT_BUCKET_NAME}/refs/*
  
  GCP Publish Site:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: "GCP Publish Site"
          command: |
            source .circleci/cicd-definitions.sh
            echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
            gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
            gcloud config set project ${GCLOUD_PROJECT_ID}
            gsutil web set -m index.html gs://${GCLOUD_PROJECT_BUCKET_NAME}

  GCP Revoke Credentials:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - <<: *revoke-sa

workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Prepare Credentials
      - GCP Sync:
          <<: *only-releasable
          requires:
            - Prepare Credentials
      - GCP Bucket Update:
          <<: *only-releasable
          requires:
            - GCP Sync
      - GCP Publish Site:
          <<: *only-releasable
          requires:
            - GCP Bucket Update
      - GCP Revoke Credentials:
          requires:
            - Prepare Credentials
