version: 2.1

jobs:
  test:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/PROJECT_TEST
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            echo PROJECT_TEST
            gcloud --version
            echo $GCP_KEY | gcloud auth activate-service-account \
                  constru-carvalho@dynamic-nomad-223612.iam.gserviceaccount.com --key-file=./del.json
            gcloud config set project dynamic-nomad-223612
            
  
workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - test
