version: 2.1

jobs:
  test:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/PROJECT_TEST
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            echo PROJECT_TEST
            echo ${GCP_KEY} | tee del.json
            gcloud auth -q activate-service-account --key-file del.json
            gcloud config -q set project dynamic-nomad-223612
            gcloud app deploy -q app.yaml
            #gcloud components update
            #gcloud config configurations list
            #echo ${GCP_KEY} > ${HOME}/gcp-key.json
            #gcloud auth -q activate-service-account --key-file ${HOME}/gcp-key.json
            
  
workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - test
